config/routes.rb
Spree::Core::Engine.routes.draw do
  get 'home/index'

  resources :products, :only => [:index, :show]

  # # non-restful checkout stuff
  # patch '/checkout/update/:state', :to => 'checkout#update', :as => :update_checkout
  # get '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state
  # get '/checkout', :to => 'checkout#edit' , :as => :checkout


  # get '/orders/populate', :to => populate_redirect
  # get '/orders/:id/token/:token' => 'orders#show', :as => :token_order

  # resources :orders, :except => [:new, :create, :destroy] do
  #   post :populate, :on => :collection
  # end

  # get '/cart', :to => 'orders#edit', :as => :cart
  # patch '/cart', :to => 'orders#update', :as => :update_cart
  # put '/cart/empty', :to => 'orders#empty', :as => :empty_cart

  # # route globbing for pretty nested taxon and product paths
  # get '/t/*id', :to => 'taxons#show', :as => :nested_taxons

  # get '/unauthorized', :to => 'home#unauthorized', :as => :unauthorized
  # get '/content/cvv', :to => 'content#cvv', :as => :cvv
  # get '/content/*path', :to => 'content#show', :as => :content
end

app/controllers/spree/home_controller.rb
module Spree
  class HomeController < Spree::StoreController
    helper 'spree/products'
    respond_to :html

    def index
      @searcher = build_searcher(params)
      @products = @searcher.retrieve_products

      render 'templates/index'
    end
  end
end

app/controllers/spree/products_controller.rb
module Spree
  class ProductsController < Spree::StoreController
    before_filter :load_product, :only => :show
    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    helper 'spree/taxons'

    respond_to :html

    def index
      @searcher = build_searcher(params)
      @products = @searcher.retrieve_products
    end

    def show
      return unless @product

      @variants = @product.variants_including_master.active(current_currency).includes([:option_values, :images])
      @product_properties = @product.product_properties.includes(:property)

      referer = request.env['HTTP_REFERER']
      if referer
        begin
          referer_path = URI.parse(request.env['HTTP_REFERER']).path
          # Fix for #2249
        rescue URI::InvalidURIError
          # Do nothing
        else
          if referer_path && referer_path.match(/\/t\/(.*)/)
            @taxon = Spree::Taxon.find_by_permalink($1)
          end
        end
      end
    end

    private
      def accurate_title
        @product ? @product.name : super
      end

      def load_product
        if try_spree_current_user.try(:has_spree_role?, "admin")
          @product = Product.with_deleted.find_by_permalink!(params[:id])
        else
          @product = Product.active(current_currency).find_by_permalink!(params[:id])
        end
      end
  end
end

app/controllers/spree/store_controller.rb
module Spree
  class StoreController < Spree::BaseController
    include Spree::Core::ControllerHelpers::Order

    layout 'layouts/theme'

    def unauthorized
      render 'spree/shared/unauthorized', :layout => Spree::Config[:layout], :status => 401
    end

    protected
      # This method is placed here so that the CheckoutController
      # and OrdersController can both reference it (or any other controller
      # which needs it)
      def apply_coupon_code
        if params[:order] && params[:order][:coupon_code]
          @order.coupon_code = params[:order][:coupon_code]

          handler = PromotionHandler::Coupon.new(@order).apply

          if handler.error.present?
            flash.now[:error] = handler.error
            respond_with(@order) { |format| format.html { render :edit } } and return
          elsif handler.success
            flash[:success] = handler.success
          end
        end
      end

      def config_locale
        Spree::Frontend::Config[:locale]
      end
  end
end

app/helpers/spree/home_helper.rb
module Spree::HomeHelper
end

app/views/layouts/theme.html.erb
<!doctype html>
<!--[if lt IE 7 ]> <html class="ie ie6" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie ie9" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if gt IE 9]><!--><html lang="<%= I18n.locale %>"><!--<![endif]-->
  <head data-hook="inside_head">
    <%= render partial: 'snippets/head' %>
  </head>

  <body class="<%= body_class %>" id="<%= @body_id || 'default' %>" data-hook="body">

    <div class="container">

    <header id="header" class="row" data-hook>
      <figure id="logo" class="columns six" data-hook><%= logo %></figure>

      <% @taxons = @taxon && @taxon.parent ? @taxon.parent.children : Spree::Taxon.roots %>
      <%= form_tag spree.products_path, :method => :get do %>
        <%= select_tag :taxon,
              options_for_select([[Spree.t(:all_departments), '']] +
                                    @taxons.map {|t| [t.name, t.id]},
                                    @taxon ? @taxon.id : params[:taxon]), 'aria-label' => 'Taxon' %>
        <%= search_field_tag :keywords, params[:keywords], :placeholder => Spree.t(:search) %>
        <%= submit_tag Spree.t(:search), :name => nil %>
      <% end %>

      <% if store_menu? %>
      <nav class="columns sixteen">
        <ul id="main-nav-bar" class="inline" data-hook>
          <li id="home-link" data-hook><%= link_to Spree.t(:home), spree.root_path %></li>
          <li id="link-to-cart" data-hook><%= link_to_cart %></li>
        </ul>
      </nav>
      <% end %>

    </header>

      <div id="wrapper" class="row" data-hook>

        <%= breadcrumbs(@taxon) %>

        <% if content_for? :sidebar %>
        <aside id="sidebar" data-hook>
          <%= yield :sidebar %>
        </aside>
        <% end %>

        <div id="content" data-hook>
          <%= flash_messages %>
          <%= yield %>
        </div>

        <%= yield :templates %>

      </div>

      <footer id="footer" data-hook>
        <div id="footer-left" data-hook>
          <%= Spree.t :powered_by  %> <%= link_to 'Spree', 'http://spreecommerce.com/' %>
        </div>
        <div id="footer-right" data-hook></div>
      </footer>

    </div>

    <%= render partial: 'snippets/google_analytics' %>
    <script>
      Spree.api_key = <%= raw(try_spree_current_user.try(:spree_api_key).to_s.inspect) %>;
    </script>
  </body>
</html>

app/views/snippets/_cart_form.html.erb
<%= form_for :order, :url => populate_orders_path do |f| %>
  <div id="inside-product-cart-form" data-hook="inside_product_cart_form" itemprop="offers" itemscope itemtype="http://schema.org/Offer">

    <% if @product.variants_and_option_values(current_currency).any? %>
      <div id="product-variants">
        <h6><%= Spree.t(:variants) %></h6>
        <ul>
          <% @product.variants_and_option_values(current_currency).each_with_index do |variant, index| %>
            <li>
              <%= radio_button_tag "variant_id", variant.id, index == 0, 'data-price' => display_price(variant) %>
              <%= label_tag "variant_id" do %>
                <span>
                  <%= variant_options variant %>
                </span>
                <% if variant_price variant %>
                  <span><%= variant_price variant %></span>
                <% end %>
              <% end %>
            </li>
          <% end%>
        </ul>
      </div>
    <% else %>
      <%= hidden_field_tag "variant_id", @product.master.id %>
    <% end %>

    <% if @product.price_in(current_currency) and !@product.price.nil? %>
      <div data-hook="product_price">

        <div id="product-price">
          <h6><%= Spree.t(:price) %></h6>
          <div>
            <span itemprop="price">
              <%= display_price(@product) %>
            </span>
            <span itemprop="priceCurrency" content="<%= @product.currency %>"></span>
          </div>

          <% if @product.master.in_stock? %>
            <link itemprop="availability" href="http://schema.org/InStock" />
          <% end %>
        </div>

        <div>
          <%= number_field_tag :quantity, 1, :class => 'title', :min => 1 %>
          <%= button_tag :class => 'large primary', :id => 'add-to-cart-button', :type => :submit do %>
            <%= Spree.t(:add_to_cart) %>
          <% end %>
        </div>
      </div>
    <% else %>
        <div id="product-price">
          <br>
          <div><span itemprop="price"><%= Spree.t('product_not_available_in_this_currency') %></span></div>
        </div>
    <% end %>
  </div>
<% end %>

app/views/snippets/_google_analytics.html.erb
<% if tracker = Spree::Tracker.current %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '<%= tracker.analytics_id %>');
    ga('send', 'pageview');

    <% if flash[:commerce_tracking] && @order.present? %>
      <%# more info: https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce %>
      ga('require', 'ecommerce', 'ecommerce.js');
      ga('ecommerce:addTransaction', {
        'id': '<%= j @order.number %>',                                     // Transaction ID. Required.
        'affiliation': '<%= Spree::Config[:site_name] %>',                 // Affiliation or store name.
        'revenue': '<%= @order.total %>',                                 // Grand Total.
        'shipping': '<%= @order.shipments.sum("cost + promo_total") %>', // Shipping.
        'tax': '<%= @order.all_adjustments.tax.sum(:amount) %>',        // Tax.
        'currencyCode': '<%= current_currency %>'                      // local currency code.
      });
      <% @order.line_items.each do |line_item| %>
        ga('ecommerce:addItem', {
          'id': '<%= j @order.number %>',                        // Transaction ID. Required.
          'name': '<%= j line_item.variant.product.name %>',    // Product name. Required.
          'sku': '<%= j line_item.variant.sku %>',             // SKU/code.
          'category': '',                                     // Category or variation.
          'price': '<%= line_item.price %>',                 // Unit price.
          'quantity': '<%= line_item.quantity %>'           // Quantity.
        });
      <% end %>
      ga('ecommerce:send');
    <% end %>
  </script>
<% end %>

app/views/snippets/_head.html.erb
<meta charset="utf-8">
<title><%= title %></title>

<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1" name="viewport">
<%== meta_data_tags %>
<%= csrf_meta_tags %>
<%= canonical_tag %>

<%= favicon_link_tag image_path('favicon.ico') %>
<%= stylesheet_link_tag 'store/spree_clean_theme', :media => 'screen' %>

<%= javascript_include_tag 'store/all' %>

<%= render "spree/shared/routes" %>
<%= yield :head %>

app/views/snippets/_products.html.erb
<%
  paginated_products = @searcher.retrieve_products if params.key?(:keywords)
  paginated_products ||= products
%>

<% content_for :head do %>
  <% if paginated_products.respond_to?(:num_pages) %>
    <%= rel_next_prev_link_tags paginated_products %>
  <% end %>
<% end %>

<% if products.empty? %>
  <%= Spree.t(:no_products_found) %>
<% elsif params.key?(:keywords) %>
  <h6><%= Spree.t(:search_results, :keywords => h(params[:keywords])) %></h6>
<% end %>

<% if products.any? %>
<ul id="products" data-hook>
  <% products.each do |product| %>
    <li id="product_<%= product.id %>" data-hook="products_list_item" itemscope itemtype="http://schema.org/Product">
      <div>
        <%= link_to small_image(product, :itemprop => "image"), product, :itemprop => 'url' %>
      </div>
      <%= link_to truncate(product.name, :length => 50), product, :class => 'info', :itemprop => "name", :title => product.name %>
      <span itemprop="price"><%= display_price(product) %></span>
    </li>
  <% end %>
</ul>
<% end %>

<% if paginated_products.respond_to?(:num_pages) %>
  <%= paginate paginated_products %>
<% end %>

app/views/templates/index.html.erb
<% content_for :sidebar do %>
  <div data-hook="homepage_sidebar_navigation">
    <nav id="taxonomies" class="sidebar-item" data-hook>
      <% get_taxonomies.each do |taxonomy| %>
        <%= Spree.t(:shop_by_taxonomy, :taxonomy => taxonomy.name) %>
        <%= taxons_tree(taxonomy.root, @taxon, Spree::Config[:max_level_in_taxons_menu] || 1) %>
      <% end %>
    </nav>
  </div>
<% end %>

<div data-hook="homepage_products">
  <%= render :partial => 'snippets/products', :locals => { :products => @products } %>
</div>

app/views/templates/product.html.erb
<div data-hook="product_show" itemscope itemtype="http://schema.org/Product">
  <% @body_id = 'product-details' %>

  <div data-hook="product_left_part">
    <div data-hook="product_left_part_wrap">

      <div id="product-images" data-hook="product_images">
        <div id="main-image" data-hook>
          <% if defined?(image) && image %>
            <%= image_tag image.attachment.url(:product), :itemprop => "image" %>
          <% else %>
            <%= product_image(@product, :itemprop => "image") %>
          <% end %>
        </div>
        <div id="thumbnails" data-hook>
          <%# no need for thumbnails unless there is more than one image %>
          <% if (@product.images + @product.variant_images).uniq.size > 1 %>
            <ul id="product-thumbnails" data-hook>
              <% @product.images.each do |i| %>
                <li>
                  <%= link_to(image_tag(i.attachment.url(:mini)), i.attachment.url(:product)) %>
                </li>
              <% end %>

              <% if @product.has_variants? %>
                <% @product.variant_images.each do |i| %>
                  <% next if @product.images.include?(i) %>
                  <li>
                    <%= link_to(image_tag(i.attachment.url(:mini)), i.attachment.url(:product)) %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>

      <div data-hook="product_properties">
        <% unless @product_properties.empty? %>
        <h6><%= Spree.t('properties')%></h6>
        <table id="product-properties" data-hook>
          <tbody>
            <% @product_properties.each do |product_property| %>
              <tr>
                <td><strong><%= product_property.property.presentation %></strong></td>
                <td><%= product_property.value %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
      </div>

      <div data-hook="promotions">
        <% promotions = @product.possible_promotions %>
        <% if promotions.any? %>
          <div id="promotions">
            <h3><%= Spree.t(:promotions) %></h3>
            <% promotions.each do |promotion| %>
            <div>
              <h4><%= promotion.name %></h4>
              <p><%= promotion.description %></p>
              <% if promotion.products.any? %>
              <ul>
                <% promotion.products.each do |product| %>
                  <li><%= link_to product.name, product_path(product) %></li>
                <% end %>
              </ul>
              <% end %>
            </div>
            <% end %>
          </div>
        <% end %>
      </div>

    </div>
  </div>

  <div data-hook="product_right_part">
    <div data-hook="product_right_part_wrap">

      <div id="product-description" data-hook="product_description">

        <h1 itemprop="name"><%= accurate_title %></h1>

        <div itemprop="description" data-hook="description">
          <%= product_description(@product) rescue Spree.t(:product_has_no_description) %>
        </div>

        <div id="cart-form" data-hook="cart_form">
          <%= render partial: 'snippets/cart_form' %>
        </div>

      </div>

      <%= render :partial => 'taxons' %>

    </div>
  </div>

</div>